name: Cypress Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: run tests
        run: npx cypress run --browser chrome
      - name: List report files
        run: ls -la cypress/reports

      - name: View JSON files
        run: cat cypress/reports/*.json || true

      - name: Merge Mochawesome reports
        run: npx mochawesome-merge cypress/reports/*.json > cypress/reports/report.json

      - name: Generate HTML report
        run: npx mochawesome-report-generator cypress/reports/report.json -o cypress/reports

      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-report
          path: cypress/reports/report.html
